### ISSUE TITLE
Install not working

### ISSUE THREAD

**Issue by vefjun** [PEZ/backseat-driver#2]
Hello.
I followed the instructions to install, downloaded your project, open in VS code and created the shortcut.
When using the shortcut, I get a an error:

Could not resolve symbol: backseat

**Comment by vefjun** [comment]
I see that the keyboard shortcuts should be:

;; == Keyboard shortcuts
    ;; {
    ;;     "key": "ctrl+alt+,",
    ;;     "command": "joyride.runCode",
    ;;     "args": "(backseat-driver.app/please-advice!)",
    ;; },

**Comment by PEZ** [comment]
Hi! Thanks for trying Backseat Driver, and for reporting! 🙏 I've fixed the typo now.
